language: c
os:
  - linux
  - osx
sudo: required
services:
  - docker
env:
  - ARCH=i386 ARCH_CMD=linux32
  - ARCH=x86_64 ARCH_CMD=linux64
before_install: |
  case $TRAVIS_OS_NAME in
    linux)
      docker pull jhass/crystal-build-$ARCH
      ;;
    osx)
      brew update
      brew tap manastech/crystal
      ;;
  esac
install: |
  case $TRAVIS_OS_NAME in
    osx)
      brew install gmp libevent crystal-lang
      curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-darwin-x86_64.tar.gz" | tar xz -C /tmp
      export LIBRARY_PATH="/usr/local/opt/crystal-lang/embedded/lib"
      export PATH="/tmp/llvm-3.5.0-1/bin:$PATH"
      ;;
  esac
script: |
  set -e
  case $TRAVIS_OS_NAME in
    linux)
      docker run -v $(pwd):/mnt -w /mnt jhass/crystal-build-$ARCH $ARCH_CMD make crystal spec CRYSTAL_CONFIG_VERSION="ci" LIBRARY_PATH="/opt/crystal/embedded/lib/"
      docker run -v $(pwd):/mnt -w /mnt jhass/crystal-build-$ARCH $ARCH_CMD /bin/bash -c 'find samples -name "*.cr" | xargs -L 1 ./bin/crystal build --no-codegen' CRYSTAL_CONFIG_VERSION="ci" LIBRARY_PATH="/opt/crystal/embedded/lib/"
      ;;
    osx)
      export CRYSTAL_CONFIG_VERSION="ci"
      export CRYSTAL_CACHE_DIR="/tmp/crystal"
      make crystal spec
      find samples -name "*.cr" | xargs -L 1 ./bin/crystal build --no-codegen
      ;;
  esac
branches:
  only:
    - master
    - gh-pages
notifications:
  irc:
    channels:
      - "irc.freenode.net#crystal-lang"
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{commit} (%{branch} - %{commit_subject}): %{message} %{build_url}"
  slack:
    secure: Ng3nTqGWY+9p1pS6yjGqDhmRvdgbIZgTNpMWbO/ngwpCyicmD3jafZkShqqXbULZTJJr3OxIGzi6GHGusT0Ic/Pi9JCM3X3v/xuBruKIR+EnNyPo7IL4ZYAlwnXyJHlCHHDBq0gSHGvGJwsXn6IgZBPRfeIq+CCyQHVPyvc9EHE=
matrix:
  exclude:
    - os: osx
      env: ARCH=i386 ARCH_CMD=linux32
