language: objective-c
before_install:
  - brew update
install:
  - brew install gmp
  - brew tap manastech/crystal
  - brew install crystal --with-llvm
env: CRYSTAL_CONFIG_VERSION=ci
script:
  - make crystal
  - bin/crystal spec/all_spec.cr
notifications:
  irc: "irc.freenode.net#crystal-lang"
  slack:
    secure: Ng3nTqGWY+9p1pS6yjGqDhmRvdgbIZgTNpMWbO/ngwpCyicmD3jafZkShqqXbULZTJJr3OxIGzi6GHGusT0Ic/Pi9JCM3X3v/xuBruKIR+EnNyPo7IL4ZYAlwnXyJHlCHHDBq0gSHGvGJwsXn6IgZBPRfeIq+CCyQHVPyvc9EHE=
